### ISSUE TITLE
Fix Swagger for Spring Boot V3

### ISSUE THREAD

**Issue by mamartinezmejia** [bcgov/nr-forest-client#165]
After upgrading to Spring Boot V3 the Swagger page stop working.

The API work properly, but not the Swagger page.

**Comment by MCatherine1994** [comment]
springdoc-openapi support for sprint boot 3: https://springdoc.org/v2/, migration guide: https://github.com/springdoc/springdoc-openapi-demos/wiki/springdoc-openapi-2.x-migration-guide
