### ISSUE TITLE
Personal db account for team members

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client#195]
https://apps.nrs.gov.bc.ca/int/jira/browse/SD-56183

**Comment by mamartinezmejia** [comment]
Another related one: [SD-57330](https://apps.nrs.gov.bc.ca/int/jira/browse/SD-57330)

**Comment by paulushcgcj** [comment]
Should we still pursue this @mamartinezmejia ?

**Comment by paulushcgcj** [comment]
closing this as @mamartinezmejia already got one and I don't need one
