### ISSUE TITLE
SonarCloud Project Names Inconsistent

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-forest-client#226]
SonarCloud names, mostly for display, are inconsistent.  forest-client-backend and nr-forest-client-frontend.

Figure out how to straighten this out.  Sonar args might work, `-Dsonar.projectName`, so could going to the platform team for a rename.

**Comment by paulushcgcj** [comment]
I noticed it, will make sure to include it in future releases

**Comment by DerekRoberts** [comment]
This isn't a concern.  Closing!
