### ISSUE TITLE
Developer Container on VSCode

### ISSUE THREAD

**Issue by paulushcgcj** [bcgov/nr-forest-client#241]
We can use (Developer Containers)[https://microsoft.github.io/code-with-engineering-playbook/developer-experience/devcontainers/] to streamline VSCode environment and make it easier to reproduce, by adding the correct extensions and configurations that need to be set for every developer.

Maybe this is something we can investigate in the future

**Comment by MCatherine1994** [comment]
I followed the step in this [tutorial](https://code.visualstudio.com/docs/devcontainers/create-dev-container) and created a .devcontainer/devcontainer.json file to include the following:
```
{
  "dockerFile": "Dockerfile",

  "customizations": {
    "vscode": {
      "extensions": [
        "esbenp.prettier-vscode",
        "MisterJ.vue-volar-extention-pack"
      ]
    }
  },
  "forwardPorts": [3000]
}
```

but when I'm following the step try to reopen in the container,  I got this error:
![image](https://user-images.githubusercontent.com/23131735/212749093-3b887678-0ff7-469c-8f70-254615863b8d.png)

Any idea?

**Comment by paulushcgcj** [comment]
Devcontainer implemented. The only problem is related to the node modules folder loosing it's ownership when reloading the container.
