### ISSUE TITLE
FSADT1-539: refactor frontend, add validation placeholder

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client#255]
[FSADT1-539](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-539) refactor frontend, add validation placeholder
refs: #89

[custom Global State Management](https://dev.to/manuelojeda/learn-to-create-your-custom-global-state-management-with-vue-3-11am)
[watcher](https://vuejs.org/guide/essentials/watchers.html#basic-example)

**Comment by paulushcgcj** [comment]
This was already done. Now we're working with the actual validator and creating the new URL
