### ISSUE TITLE
FSADT1-311: Enable forest client app login

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client#46]
[FSADT1-311](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-311) Enable forest client app login

SSO doc: https://github.com/bcgov/sso-keycloak/wiki/Using-Your-SSO-Client

Setup the idir and bceid login using the Common Hosted Single Sign-on (CSS) project supported by the pathfinder team:
1. Apply for the integration through this [link](https://bcgov.github.io/sso-requests/my-dashboard/integrations) to get the required credentials
2. Using the keycloak library to do the setup, for vue3 application, use [vue-keycloak package](https://github.com/dsb-norge/vue-keycloak-js#vue-3-beta), a vue3 vite example is [here](https://github.com/dsb-norge/vue-keycloak-js/blob/main/examples/vite_vue3/src/main.ts), more docs from [old growth](https://github.com/bcgov/nr-old-growth/issues/67)
3. Add the `pkceMethod: "S256"` to the init option
4. The keycloak library we use will add a $keycloak property to the global Vue instance, to logout, could just call `$keycloak.logoutFn`

**Comment by MCatherine1994** [comment]
a test example for what bceid user returns:
![image](https://user-images.githubusercontent.com/23131735/191381031-fb41c037-ba91-4e3e-9612-6fd1f430f371.png)

**Comment by paulushcgcj** [comment]
Implemented using keycloak and now moving to FAM
