### ISSUE TITLE
Pipeline support: unit test scripts for different languages

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client#54]
Shall we please have unit test that could run for different programming languages? We are currently having java backend, and nodes frontend. Thanks!

**Comment by DerekRoberts** [comment]
@MCatherine1994 Thanks for the suggestion!  It's now in the top of the product backlog.  :)

**Comment by DerekRoberts** [comment]
Action for unit tests with java support.
https://github.com/bcgov-nr/action-test-and-analyse-java
