### ISSUE TITLE
feat: vanity url

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-forest-client#849]
Still very TBD.  I expect to need lots of help from @paulushcgcj and @mamartinezmejia.

https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-22467

https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Generating+a+CSR

https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1154

https://ssbc-client.gov.bc.ca/services/SSLCert/order.htm

Current request
https://apps.nrs.gov.bc.ca/int/jira/browse/SD-103475

**Comment by webgismd** [comment]
the last link above is handled by NRIDS INFRA team .. via an iStore request to OCIO

**Comment by webgismd** [comment]
also note.. 
Vanity URL -- one time setup
SSL Cert -- an annual party time
