### ISSUE TITLE
chore(ci): drop init

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-forest-client#863]
Init is no longer required.  Vars can be handled in separate deployments.

**Comment by paulushcgcj** [comment]
Can you expand on this? As of today, we're using the init to set things, such as secrets before everything else is deployed. Do you mean the init workflow step? If so, yeah it makes sense, as we can add this deployment before all other deployments as we do in our PR

**Comment by DerekRoberts** [comment]
@paulushcgcj We'd probably roll init and database together, simplifying config.  It's been a while, so very TBD.  :P

**Comment by DerekRoberts** [comment]
We're going to be moving to Helm, so I think this work can more or less be rolled in then.  Closing.
