### ISSUE TITLE
Get forest clients by a list of forest clients

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-forest-client#931]
**As a** *forest client api user* **I want** *to be able to submit a list of forest client ids* **So that** *the endpoint returns me a list of matching forest clients*

**Comment by paulushcgcj** [comment]
Closing issue to reopen it in the correct repo

**Comment by paulushcgcj** [comment]
Issue reopen at [nr-forest-client-api](https://github.com/bcgov/nr-forest-client-api/issues/217)
